# Change these first
owner: surgeoftheages # Your GitHub organization or username, where this repository lives
repo: sasup # The name of this repository

sites:
  - name: Aurosociety  
    url: https://aurosociety.org
  - name: Aurobharati
    url: https://aurobharati.in
  - name: AuroPublications 
    url: https://auropublications.org
  - name: Renaissance
    url: https://journal.aurobharati.in
  - name: Sanjeevan
    url: https://sanjeevanpalliativecare.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: ebook.aurosociety.org
  baseUrl: /sasup
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://ebook.aurosociety.org/sasup/sas-symbol.png
  name: Sri Aurobindo Society - UpTime
  introTitle: "You can see here all the service availability status"
  introMessage: This is a status tracking page which uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: This page is powered by [SAS IT team](https://aurosociety.org)
